name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t asumancw/nodejs-app  .
      - name: message
        run: echo "docker check..................."
      - name: directory list
        run: docker images
      - name: docker push control
        run: docker pull asumancw/blue 
      - name: Publish Image to docker hub
        run: docker push asumancw/nodejs-app:latest 
      
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull asumancw/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' asumancw/nodejs-app
